# api/config/api_platform/user_recover_password.yaml
App\Entity\Security\UserRecoverPassword:
    collectionOperations:
        recover-password:
            controller: 'App\Controller\Security\RecoverPasswordAction'
            method: post
            denormalization_context: {groups: ["user:get:recover:password"]}
            path: 'user/recover-password/{token}'
            openapi_context:
                summary: Recover Password 2nd step
                description: Recover Password 2nd step
                consumes:
                    - application/json
                parameters:
                    - in: body
                      name: Password Data
                      description: Password Data.
                      schema:
                        type: object
                        required:
                          - newPassword
                          - repeatPassword
                        properties:
                            newPassword:
                                type: string
                            repeatPassword:
                                type: object
        account_reset_password_email:
            method: post
            denormalization_context: {groups: ["user:get:recover"]}
            path: 'user/reset-password'
            openapi_context:
                summary: Recover Password 1st step
                description: Recover Password 1st step
                consumes:
                    - application/json
                parameters:
                    - in: body
                      name: Password Data
                      description: Password Data.
                      schema:
                        type: object
                        required:
                          - email
                        properties:
                            email:
                                type: string
    itemOperations:
        get:
            controller: 'ApiPlatform\Core\Action\NotFoundAction'
            read: false
            output: false
