api_platform:
    show_webby: true
    enable_docs: false
    enable_entrypoint: false
    mapping:
        #paths: ['%kernel.project_dir%/src/Entity']
        paths: ['%kernel.project_dir%/config/api_platform','%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
              name: Authorization
              type: header

    collection:
        pagination:
            client_enabled: true
            enabled_parameter_name: pagination # optional