tchoulom_view_counter:
    view_counter:
        view_strategy: hourly_view
    statistics:
        use_stats: false
        stats_file_name: stats
        stats_file_extension: txt
    storage:
        service: