twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        frontend_url: '%env(FRONTEND_URL)%'
    form_themes: [ 'bootstrap_3_layout.html.twig', '@SonataForm/Form/datepicker.html.twig' ]
