vich_uploader:
    db_driver: orm

    mappings:
        articule_media:
            uri_prefix: /images/articule_media
            upload_destination: '%kernel.project_dir%/public/images/articule_media'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            delete_on_remove: true
            delete_on_update: true

        files:
            uri_prefix: upload/pdf
            upload_destination: '%kernel.project_dir%/public/upload/pdf'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            delete_on_remove: true
            delete_on_update: true
